# Site settings
title: Shahin Katebi
description: Software Engineer, Entrepreneur
# baseurl: "" #
# url: "https://shaahin.us" #

# User settings
username: Shahin Katebi
user_description: Co-founder at Beam IT Logistics, <br>Senior macOS Engineer at Malwarebytes
user_title: Software Engineer, Entrepreneur
user_details: "PGP: 0x73B5CF3B5E02E82C<br>Signal: +1 (347) 202-1007"
email: katebi@me.com
twitter_username: ShahinKatebi
github_username:  shaahin

# Google-analytics
google-analytics:
  id: "UA-26880890-1"

exclude: ['package.json', 'src' , 'node_modules']

sass:
  style: compact
