# Site settings
title: Shahin Katebi
description: Software Engineer, Entrepreneur
# baseurl: "" #
# url: "https://shaahin.us" #

# User settings
username: Shahin Katebi
user_description: Co-founder at Beam IT Logistics and Seeb Co OÜ, <br>Software Developer
user_title: Software Engineer, Entrepreneur
email: katebi@me.com
twitter_username: ShahinKatebi
github_username:  shaahin

# Google-analytics
google-analytics:
  id: "UA-26880890-1"

exclude: ['package.json', 'src' , 'node_modules']

sass:
  style: compact